/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mock from "./mock";
export type { mock };
export type { EcoEarn } from "./EcoEarn";
export type { SozoNFT } from "./SozoNFT";
