/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { B3TR_Mock } from "./B3TR_Mock";
export type { X2EarnAppsMock } from "./X2EarnAppsMock";
export type { X2EarnRewardsPoolMock } from "./X2EarnRewardsPoolMock";
