name: Unit Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm run test
